// Converts the JSON exported by DS Sync (from Figma) into CSS variables
// with mode support (light by default, dark via prefers-color-scheme).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const INPUT = "./tokens-from-figma.json";
const OUTPUT = "./dist/tokens.css";

const tokens = JSON.parse(readFileSync(INPUT, "utf8"));

// Flattens the JSON tree. Returns two dictionaries:
// - flat: tokens with a single value (primitives or single-mode semantic)
// - modes: tokens with per-mode value { light: "...", dark: "..." }
function flatten(obj, path = [], flat = {}, modes = {}) {
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;
    const fullPath = [...path, key].join(".");
    if (value && typeof value === "object" && "$value" in value) {
      const v = value.$value;
      if (v && typeof v === "object" && !Array.isArray(v)) {
        modes[fullPath] = v;
      } else {
        flat[fullPath] = v;
      }
    } else if (value && typeof value === "object") {
      flatten(value, [...path, key], flat, modes);
    }
  }
  return { flat, modes };
}

const { flat, modes } = flatten(tokens);

function resolveLiteral(value, seen = new Set()) {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    if (seen.has(ref)) throw new Error(`Circular reference at {${ref}}`);
    if (!(ref in flat)) throw new Error(`Unknown token: {${ref}}`);
    return resolveLiteral(flat[ref], new Set([...seen, ref]));
  });
}

const cssVarFor = (name) => "--" + name.replace(/\./g, "-");

const lines = [
  "/* Generated by build.mjs from tokens-from-figma.json (DS Sync export) */",
  "",
  "/* Light mode (default) */",
  ":root {",
];

for (const [name, value] of Object.entries(flat)) {
  lines.push(`  ${cssVarFor(name)}: ${resolveLiteral(value)};`);
}
for (const [name, byMode] of Object.entries(modes)) {
  if (byMode.light) {
    lines.push(`  ${cssVarFor(name)}: ${resolveLiteral(byMode.light)};`);
  }
}
lines.push("}", "");

lines.push("/* Dark mode (OS preference) */");
lines.push("@media (prefers-color-scheme: dark) {");
lines.push("  :root {");
for (const [name, byMode] of Object.entries(modes)) {
  if (byMode.dark) {
    lines.push(`    ${cssVarFor(name)}: ${resolveLiteral(byMode.dark)};`);
  }
}
lines.push("  }", "}", "");

lines.push("/* Dark mode (manual override via class, useful for in-product toggle) */");
lines.push("[data-theme=\"dark\"] {");
for (const [name, byMode] of Object.entries(modes)) {
  if (byMode.dark) {
    lines.push(`  ${cssVarFor(name)}: ${resolveLiteral(byMode.dark)};`);
  }
}
lines.push("}");

mkdirSync("./dist", { recursive: true });
writeFileSync(OUTPUT, lines.join("\n") + "\n");
console.log(`Generated ${OUTPUT} with ${Object.keys(flat).length} primitives and ${Object.keys(modes).length} semantic with modes.`);
